/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.attendance_system;

import DATABASE.ConnectMsAccess;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author sharon
 */
public class Login_Form extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;   
    ResultSet rs = null;

    public Login_Form() {
        initComponents();
        conn = ConnectMsAccess.conn();
        
        
        user_name.setBackground(new java.awt.Color(0, 0, 0, 1));
        password.setBackground(new java.awt.Color(0, 0, 0, 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pas = new javax.swing.JLabel();
        usir1 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        RegisterBotton = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("___________________________________________");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("___________________________________________");
        jLabel6.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("__________________________________________");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 310, 10));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("__________________________________________");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 310, 10));

        pas.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        pas.setForeground(new java.awt.Color(51, 51, 51));
        pas.setText("Password");
        pas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pasFocusGained(evt);
            }
        });
        pas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasMouseClicked(evt);
            }
        });
        getContentPane().add(pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 90, 20));

        usir1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        usir1.setForeground(new java.awt.Color(51, 51, 51));
        usir1.setText("Username");
        usir1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usir1FocusGained(evt);
            }
        });
        usir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usir1MouseClicked(evt);
            }
        });
        getContentPane().add(usir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 90, 20));

        user_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        user_name.setBorder(null);
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 280, 30));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 280, 30));

        RegisterBotton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisterBotton.setForeground(new java.awt.Color(0, 0, 0));
        RegisterBotton.setText("Register");
        RegisterBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterBottonMouseClicked(evt);
            }
        });
        getContentPane().add(RegisterBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 50, 20));

        password.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        password.setBorder(null);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 280, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Don't have an account?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 150, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharon\\Downloads\\marilag (1).png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_user_nameActionPerformed

    private void pasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_pasMouseClicked

    private void pasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pasFocusGained
        // TODO add your handling code here:
        pas.setText(null);
    }//GEN-LAST:event_pasFocusGained

    private void usir1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usir1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_usir1FocusGained

    private void usir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usir1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = user_name.getText();
        char[] pass = password.getPassword();
        String userpassword = String.valueOf(pass);

        try {
            String sqlquery = "SELECT  * FROM Table 1 WHERE user_name = ? AND password = ?";
            pst = conn.prepareStatement(sqlquery);
            pst.setString(1, username);
            pst.setString(2, userpassword);
            rs = pst.executeQuery();
           if (!rs.next()){
               JOptionPane.showMessageDialog(null, "Username and Password is Incorrect!");
               }else{
               JOptionPane.showMessageDialog(null, "Login Successful");
              
               
           }
           }catch(SQLException e){
                   JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegisterBottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBottonMouseClicked
        new Sign_up().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_RegisterBottonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegisterBotton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel pas;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField user_name;
    private javax.swing.JLabel usir1;
    // End of variables declaration//GEN-END:variables

    void setVisibe(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
