/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.attendance_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;



/**
 *
 * @author sharon
 */
public class Sign_up extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Sign_up
     */
    public Sign_up() {
        initComponents();
      a1.setBackground(new java.awt.Color (0, 0, 0, 1));  
      a2.setBackground(new java.awt.Color (0, 0, 0, 1));   
      a3.setBackground(new java.awt.Color (0, 0, 0, 1)); 
      a4.setBackground(new java.awt.Color (0, 0, 0, 1)); 
      a5.setBackground(new java.awt.Color (0, 0, 0, 1)); 
      a6.setBackground(new java.awt.Color (0, 0, 0, 1)); 
      a7.setBackground(new java.awt.Color (0, 0, 0, 1)); 
      a8.setBackground(new java.awt.Color (0, 0, 0, 1)); 
      a9.setBackground(new java.awt.Color (0, 0, 0, 1)); 
      a10.setBackground(new java.awt.Color (0, 0, 0, 1)); 
       a11.setBackground(new java.awt.Color (0, 0, 0, 1));
       a12.setBackground(new java.awt.Color (0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        a6 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        a5 = new com.toedter.calendar.JDateChooser();
        a8 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        a9 = new javax.swing.JTextField();
        a11 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        a12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Last Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 80, -1));

        a2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 150, 30));

        a4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Section/Strand");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contact No#");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Guardian Contact No#");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 100, 20));

        a6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 150, 30));

        a7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 150, 30));

        a1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 150, 30));

        a10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        getContentPane().add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 340, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Email Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 100, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Student No#");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Birthday");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("First Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 80, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Password");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 130, -1));

        a5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 150, 30));

        a8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 150, 30));

        a3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 170, 30));

        a9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        getContentPane().add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 340, 30));
        getContentPane().add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 442, 150, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Guardian Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 130, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Username");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 130, -1));

        a12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        a12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        a12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a12ActionPerformed(evt);
            }
        });
        getContentPane().add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 150, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharon\\Downloads\\rrreeg.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1300, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String uname    , upass, fname, lname, snumber, ss, bdate, cnumber, gname, cnumbers, email, address;
        fname = a1.getText();
        lname = a2.getText();
        snumber = a3.getText();
        ss = a4.getText();
        bdate = (a5.getDate() != null) ? new SimpleDateFormat("MM-dd-yyyy").format(a5.getDate()) : "";
        cnumber = a6.getText();
        gname = a7.getText();
        cnumbers = a8.getText();
        email = a9.getText();
        address = a10.getText();
        upass = String.valueOf(a11.getPassword());
        uname = a12.getText();
        
        try {
            String sql = "INSERT INTO Table1 (user_name, password, first_name, last_name, student_number, email_address, student_contact_number, guardian_number, address, grade_section, birthday) "
                    + "VALUES ('" + uname + "','" + upass + "','" + fname + "', '" + lname + "', '" + snumber + "', '" + email + "', '" + cnumber + "', '" + cnumbers+ "', '" + gname + "', '" + address + "', '" + ss + "', '" + bdate+ "')";
            pst = conn.prepareStatement(sql);
            pst.execute(); 
             JOptionPane.showMessageDialog(null, "Sign up Successfully!");
            a1.setText("");
            a2.setText("");
            a3.setText("");
            a4.setText("");
            a5.setDate(null);
            a6.setText("");
            a7.setText("");
            a8.setText("");
            a9.setText("");
            a10.setText("");
            a9.setText("");
            a12.setText("");
            
        } catch (SQLException e) {
} 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login_Form().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void a12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a10;
    private javax.swing.JPasswordField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private com.toedter.calendar.JDateChooser a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
