package com.mycompany.attendancesystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author sharon
 */
public class Login extends javax.swing.JFrame {

    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        conn =  AttendanceSystem.conn();
        
         a1.setBackground(new java.awt.Color(0, 0, 0, 1));
        a1.setOpaque(false);
        a2.setBackground(new java.awt.Color(0, 0, 0, 1));
        a2.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        a2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RegisterBotton = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Password");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        lbl2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Username");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, -1, -1));
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 290, 30));

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LOGIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 290, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Don't have an account?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 150, 20));

        RegisterBotton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisterBotton.setForeground(new java.awt.Color(0, 0, 0));
        RegisterBotton.setText("Register");
        RegisterBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterBottonMouseClicked(evt);
            }
        });
        getContentPane().add(RegisterBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 50, 20));
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharon\\Downloads\\marilag (1).png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBottonMouseClicked
         new Register().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_RegisterBottonMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String username = a1.getText();
        char[] pass = a2.getPassword();
        String userpassword = String.valueOf(pass);
        
        try {
            String sqlquery = "SELECT  * FROM LOGIN WHERE user_name = ? AND password = ?";
            pst = conn.prepareStatement(sqlquery);
            pst.setString(1, username);
            pst.setString(2, userpassword);
            rs = pst.executeQuery();
           if (!rs.next()){
               JOptionPane.showMessageDialog(null, "Username and Password is Incorrect!");
               }else{
               JOptionPane.showMessageDialog(null, "Login Successful");
                   this.dispose(); 
new RFID().setVisible(true);

              
               
           }
           }catch(SQLException e){
                   JOptionPane.showMessageDialog(null, e);
        }
                 
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegisterBotton;
    private javax.swing.JTextField a1;
    private javax.swing.JPasswordField a2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
